name: "CI"
on:
  # Run only when pushing to master branch, and making PRs
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [x86_64-linux, aarch64-linux, aarch64-darwin]
    steps:
      - uses: actions/checkout@v4
      - name: Build all flake outputs
        run: om ci
